module.exports = {
	combat: [
		{ value: 'block', name: 'Block' },
		{ value: 'armorer', name: 'Armorer' },
		{ value: 'medium-armor', name: 'Medium Armor' },
		{ value: 'heavy-armor', name: 'Heavy Armor' },
		{ value: 'blunt-weapon', name: 'Blunt Weapon' },
		{ value: 'long-blade', name: 'Long Blade' },
		{ value: 'axe', name: 'Axe' },
		{ value: 'spear', name: 'Spear' },
		{ value: 'athletics', name: 'Athletics' },
	],
	magic: [
		{ value: 'enchant', name: 'Enchant' },
		{ value: 'destruction', name: 'Destruction' },
		{ value: 'alteration', name: 'Alteration' },
		{ value: 'illusion', name: 'Illusion' },
		{ value: 'conjuration', name: 'Conjuration' },
		{ value: 'mysticism', name: 'Mysticism' },
		{ value: 'restoration', name: 'Restoration' },
		{ value: 'alchemy', name: 'Alchemy' },
		{ value: 'unarmored', name: 'Unarmored' },
	],
	stealth: [
		{ value: 'security', name: 'Security' },
		{ value: 'sneak', name: 'Sneak' },
		{ value: 'acrobatics', name: 'Acrobatics' },
		{ value: 'light-armor', name: 'Light Armor' },
		{ value: 'shortblade', name: 'Short Blade' },
		{ value: 'marksman', name: 'Marksman' },
		{ value: 'mercantile', name: 'Mercantile' },
		{ value: 'speechcraft', name: 'Speechcraft' },
		{ value: 'hand-to-hand', name: 'Hand to Hand' },
	],
};