module.exports = {
	combat: {
		'block': 'Block',
		'armorer': 'Armorer',
		'medium-armor': 'Medium Armor',
		'heavy-armor': 'Heavy Armor',
		'blunt-weapon': 'Blunt Weapon',
		'long-blade': 'Long Blade',
		'axe': 'Axe',
		'spear': 'Spear',
		'athletics': 'Athletics',
	},
	magic: {
		'enchant': 'Enchant',
		'destruction': 'Destruction',
		'alteration': 'Alteration',
		'illusion': 'Illusion',
		'conjuration': 'Conjuration',
		'mysticism': 'Mysticism',
		'restoration': 'Restoration',
		'alchemy': 'Alchemy',
		'unarmored': 'Unarmored',
	},
	stealth: {
		'security': 'Security',
		'sneak': 'Sneak',
		'acrobatics': 'Acrobatics',
		'light-armor': 'Light Armor',
		'shortblade': 'Short Blade',
		'marksman': 'Marksman',
		'mercantile': 'Mercantile',
		'speechcraft': 'Speechcraft',
		'hand-to-hand': 'Hand to Hand',
	},
};